[package]
name = "egomoose/fractality-spring"
description = "https://github.com/EgoMoose/rbx-fractality-spring"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["Fractality", "EgoMoose"]
license = "MIT"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE"]
private = true